//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial_Manager_V0._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        public string Client1 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int Telephone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
