//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial_Manager_V0._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAccount
    {
        public int Id { get; set; }
        public string ClientName_ { get; set; }
        public string AccountType { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public int InvoiceNo { get; set; }
        public System.DateTime Date { get; set; }
    }
}
